import colors            from 'ansi-colors'
import log               from 'fancy-log'
import { writeFileSync } from 'fs'
import {
    basename,
    join,
    relative
}                        from 'path'
import {
    getConfigurationFrom,
    getConfigurationPathFor,
    getFilesFrom,
    iteePackageConfigurationsDirectory,
    packageRootDirectory,
    packageTasksConfigurationsDirectory
} from './_utils.mjs'

const {
          green,
          yellow
      } = colors

const configurationPath     = getConfigurationPathFor( 'refresh.conf.mjs' )
const configuration         = await getConfigurationFrom( configurationPath )

// Get and filter tasks to expose
const defaultTaskFiles = [
    'buildTask',
    'cleanTask',
    'docTask',
    'helpTask',
    'lintTask',
    'patchTask',
    'releaseTask',
    'runTestsTask',
    'computeUnitTestsTask',
    'runUnitTestsTask',
    'runUnitTestsForBackendTask',
    'runUnitTestsForFrontendTask',
    'checkBundlingFromEsmBuildImportTask',
    'checkBundlingFromEsmFilesDirectTask',
    'checkBundlingFromEsmFilesImportTask',
    'checkBundlingTask',
    'computeBenchmarksTask',
    'runBenchmarksTestsTask',
    'runBenchmarksForBackendTask',
    'runBenchmarksForFrontendTask',
].filter( taskName => {
    const included = !configuration.includes( taskName )

    included
    ? log( 'Include default', green( taskName ) )
    : log( 'Exclude default', yellow( taskName ) )

    return included
} )

const userTaskFiles = getFilesFrom(
    join( packageRootDirectory, '.tasks/{.*.task.mjs,*.task.mjs,.**/*.task.mjs,.**/**/*.task.mjs}' ),
    filePath => {
        const relativeFilepath = relative( packageRootDirectory, filePath )
        const filename         = basename( filePath )
        const included         = !configuration.includes( filename )

        included
        ? log( 'Include', green( relativeFilepath ) )
        : log( 'Exclude', yellow( relativeFilepath ) )

        return included
    }
)

// Prepare gulpfile content with header
let gulpfileContent = '' +
    '/**\n' +
    ' * This file is auto-generated by internal gulp command.\n' +
    ' * If you want to customize the available gulp tasks, create your own in .tasks folder\n' +
    ' * and run "gulp refresh"\n' +
    ' */\n\n'

// Generate default tasks exports and append to gulpfile content
gulpfileContent += '// Default Itee tasks\n'
for ( const taskName of defaultTaskFiles ) {
    gulpfileContent += `export { ${ taskName } } from 'itee-tasks'\n`
}

gulpfileContent += '\n'

// Generate user tasks exports and append to gulpfile content
gulpfileContent += '// User defined tasks\n'
for ( const taskFile of userTaskFiles ) {
    const relativeTaskFile = relative( packageRootDirectory, taskFile )
    gulpfileContent += `export * from './${ relativeTaskFile }'\n`
}

// Create gulpfile file
const gulpfilePath = join( packageRootDirectory, 'gulpfile.mjs' )
log( 'Refresh', green( gulpfilePath ) )
writeFileSync( gulpfilePath, gulpfileContent )
