import { writeFileSync }           from 'node:fs'
import {
    basename,
    join,
    relative
}                                  from 'node:path'
import {
    green,
    yellow
}                                  from '../sources/utils/colors.mjs'
import { getFilesFrom }            from '../sources/utils/files.mjs'
import { log }                     from '../sources/utils/loggings.mjs'
import {
    iteePackageRootDirectory,
    iteePackageSourcesDirectory,
    packageNodeModulesDirectory,
    packageRootDirectory,
    packageTasksDirectory
}                                  from '../sources/utils/packages.mjs'
import { getTaskConfigurationFor } from '../sources/utils/tasks.mjs'

const configuration = await getTaskConfigurationFor( import.meta.filename )

// Get and filter tasks to expose
const defaultTaskPattern = join( iteePackageSourcesDirectory, '/{*.task.mjs,**/*.task.mjs,**/**/*.task.mjs}' )
const defaultTaskFiles   = getFilesFrom(
    defaultTaskPattern,
    filePath => {
        const relativeFilepath = relative( iteePackageSourcesDirectory, filePath )
        const filename         = basename( filePath )
        const included         = !configuration.includes( filename )

        included
        ? log( 'Include default task from', green( relativeFilepath ) )
        : log( 'Exclude default task from', yellow( relativeFilepath ) )

        return included
    }
)

const userTaskPattern = join( packageTasksDirectory, '/{*.task.mjs,**/*.task.mjs,**/**/*.task.mjs}' )
const userTaskFiles   = getFilesFrom(
    userTaskPattern,
    filePath => {
        const relativeFilepath = relative( packageRootDirectory, filePath )
        const filename         = basename( filePath )
        const included         = !configuration.includes( filename )

        included
        ? log( 'Include user task from', green( relativeFilepath ) )
        : log( 'Exclude user task from', yellow( relativeFilepath ) )

        return included
    }
)

// Prepare gulpfile content with header
let gulpfileContent = '' +
    '/**\n' +
    ' * This file is auto-generated by internal gulp command.\n' +
    ' * If you want to customize the available gulp tasks, create your own in .tasks folder\n' +
    ' * and run "gulp refresh"\n' +
    ' */\n\n'

// Generate default tasks exports and append to gulpfile content
gulpfileContent += '// Default Itee tasks\n'
for ( const taskFile of defaultTaskFiles ) {

    // we are calling from client and use relative path from it
    if ( iteePackageRootDirectory.includes( 'node_modules' ) ) {

        const relativeTaskFile = relative( packageNodeModulesDirectory, taskFile )
        gulpfileContent += `export * from '${ relativeTaskFile }'\n`

    } else { // we are refreshing itee-tasks package internally

        const relativeTaskFile = relative( iteePackageRootDirectory, taskFile )
        gulpfileContent += `export * from './${ relativeTaskFile }'\n`

    }

}

gulpfileContent += '\n'

// Generate user tasks exports and append to gulpfile content
if ( userTaskFiles.length > 0 ) {
    gulpfileContent += '// User defined tasks\n'
}
for ( const taskFile of userTaskFiles ) {
    const relativeTaskFile = relative( packageRootDirectory, taskFile )
    gulpfileContent += `export * from './${ relativeTaskFile }'\n`
}

// Create gulpfile file
const gulpfilePath = join( packageRootDirectory, 'gulpfile.mjs' )
log( 'Refresh', green( gulpfilePath ) )
writeFileSync( gulpfilePath, gulpfileContent )
